######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 20 11:59:32 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += kfile.h pictureflow.h
SOURCES += kfile.cpp main.cpp pictureflow.cpp
